# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-12 07:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191112_1121'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='create_time',
            new_name='created_time',
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='update_time',
            new_name='updated_time',
        ),
    ]
