# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-12 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('company', models.CharField(max_length=100, unique=True, verbose_name='公司名')),
                ('email', models.CharField(max_length=200, verbose_name='邮箱名')),
                ('start_time', models.DateTimeField(verbose_name='生效时间')),
                ('end_time', models.DateTimeField(verbose_name='终止时间')),
            ],
            options={
                'verbose_name': '企业信息',
                'verbose_name_plural': '企业信息',
                'db_table': 'company',
            },
        ),
    ]
