# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-12 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='companyinfo',
            name='is_alive',
            field=models.BooleanField(default=True, verbose_name='是否在有效期'),
        ),
    ]
