# -*- coding: utf-8 -*-
# Generated by Django 1.11.8 on 2019-11-12 12:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notice', '0002_companyinfo_is_alive'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('season', models.CharField(max_length=5, verbose_name='季度')),
                ('send_status', models.BooleanField(default=True, verbose_name='发送状态')),
                ('company_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='notice.CompanyInfo', verbose_name='企业ID')),
            ],
            options={
                'verbose_name': '发送记录',
                'verbose_name_plural': '发送记录',
                'db_table': 'record',
            },
        ),
    ]
